site_name: Herramienta de Ventas

theme:
  name: material
  palette:
    - scheme: default
      primary: lime         
      accent: light green  
    - scheme: slate
      primary: lime
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Presentacion Licita: Presentacion.md
  - Formulario de Cotizaci√≥n: FormCotizacion.md
  - Testimonios: Testimonios.md
