site_name: Herramienta de Ventas

theme:
  name: material
  logo: logolicita.png    
  favicon: logolicita.png
  palette:
    - scheme: default
      primary: lime
      accent: light green
    - scheme: slate
      primary: lime
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Presentacion Licita: Presentacion.md
  - Formulario de Cotizaci√≥n: FormCotizacion.md
  - Testimonios: Testimonios.md
  - Links de pago: Linkspago.md
  - Leads en seguimiento de pago: Leadspago.md
